// Generated automatically from sales_raw.csv and Excel pricelist

export const initialDSRs = [
  {
    "id": "DSR-KAN",
    "name": "กร (อุทัยธานี - ชัยนาท)",
    "phone": "081-111-2222"
  },
  {
    "id": "DSR-ANN",
    "name": "แอน (นครสวรรค์ 2)",
    "phone": "082-222-3333"
  },
  {
    "id": "DSR-NA",
    "name": "นา (สุพรรณบุรี 1)",
    "phone": "083-333-4444"
  },
  {
    "id": "DSR-MUD",
    "name": "มัดหมี่ (นครสวรรค์ 1)",
    "phone": "084-444-5555"
  },
  {
    "id": "DSR-NUCH",
    "name": "นุช (สุพรรณบุรี 2)",
    "phone": "085-555-6666"
  }
];

export const initialCustomers = [
  {
    "id": "205-344",
    "name": "ช่างเอี่ยม(พยุหะคีรี)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1903",
    "name": "ชนินทร์การยาง (2002)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "109-86",
    "name": "สุชาติยานยนต์",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "49 : อ.สรรคบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1385",
    "name": "เป็ดมอเตอร์ไซต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1901",
    "name": "เกษมการยาง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2039",
    "name": "ซุ้ม ป เป๊ปเป้",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-994",
    "name": "บริษัท พีการาจ ออโต้ เซอร์วิส จำกัด",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-898",
    "name": "ละออการช่าง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "39 : อ.แม่เปิ่น",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-134",
    "name": "ช่างเล็กกลการ",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "39 : อ.แม่เปิ่น",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1546",
    "name": "ส.ศิริยนต์ (แม่วงศ์)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "40 : อ.แม่วงก์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-485",
    "name": "/1  ร้านจวบ คาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-167",
    "name": "/1  ช่างสุวิทย์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2134",
    "name": "เอ็นเอส ออโต้ เซอร์วิส จำกัด",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-368",
    "name": "สุรพงษ์ ออโต้เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "26 : อ.ตาคลี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1749",
    "name": "ช่างกอล์ฟ",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "27 : อ.ตากฟ้า",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-454",
    "name": "ร้านสัญญาการช่าง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "27 : อ.ตากฟ้า",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1515",
    "name": "ช่างบาส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1295",
    "name": "คลีนิกรถยนต์ (ช่างสมพร)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-17",
    "name": "ดีศิริ เซอร์วิส(บุญแทน)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-315",
    "name": "ร้านวิริยะคาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-291",
    "name": "พี.เอส.ออโต้",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "30 : อ.หนองบัว",
    "segment": "ทั้งคู่"
  },
  {
    "id": "205-973",
    "name": "บริษัท วิริยะยางยนต์ (2018) จำกัด",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-1002",
    "name": "ช่างน้อยบริการ",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1016",
    "name": "วรธนคาร์เซอร์วิส",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2047",
    "name": "โอ.เค.เซอร์วิส",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2107",
    "name": "ช่างอุ๋ย",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "109-370",
    "name": "ร้านเจริญยนต์(หันคา)",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "48 : อ.หันคา",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-68",
    "name": "พะเชิญมอเตอร์ไซต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-87",
    "name": "พิณเจริญยนต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1483",
    "name": "อารีภักดิ์คาร์แคร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-170",
    "name": "อิทธิเจริญยนต์2",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-753",
    "name": "ช่างสาย",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1262",
    "name": "J.R. GARAGE",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2116",
    "name": "เวียงพิงออโต้",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1363",
    "name": "ช่างพิมพ์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "52 : อ.บ้านไร่",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1596",
    "name": "ช่างทัศน์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "52 : อ.บ้านไร่",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-179",
    "name": "ถาวรบริการ",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "52 : อ.บ้านไร่",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-270",
    "name": "ร้านเพื่อนยานยนต์2",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "52 : อ.บ้านไร่",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-147",
    "name": "พงศ์พรรณอะไหล่",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "55 : อ.สว่างอารมณ์",
    "segment": "ทั้งคู่"
  },
  {
    "id": "113-1341",
    "name": "บรรพตยานยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1775",
    "name": "ช่างคุณาสรณ์ ราตรี",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-248",
    "name": "มนัส มอเตอร์ไซค์(ร้านณัฐดอนแจง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-329",
    "name": "คุณธนัท  ก้องแดนไพร",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2131",
    "name": "ช่างต่อ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2051",
    "name": "ช่างวัดสุ1000บุรี",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-423",
    "name": "คุณโกวิทย์ แก้วเจริญ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1785",
    "name": "อู่โชคชัยเซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1110",
    "name": "อู่ช่างเล็กเซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-82",
    "name": "หจก.โชคไพบูลย์คาร์แคร์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1700",
    "name": "ช่างยุทธนา กลิ่นทอง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "02 : อ.เดิมบางนางบวช",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-16",
    "name": "คุณชูชัย  วัฒนาสุข  (ร้านอุดมยานยนต์)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2070",
    "name": "ร้านยางขวัญใจคนจน",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-715",
    "name": "/1  ร้านสมนึกคาร์ เซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1404",
    "name": "ช รุ่งเรือง อ่างทอง",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "11 : อ.เมือง อ่างทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1254",
    "name": "โชคอัมพรคาร์แคร์",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "11 : อ.เมือง อ่างทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2130",
    "name": "ห้างหุ้นส่วน อังเปารถยก",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "14 : อ.ไชโย",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1537",
    "name": "ช่างจิ้น",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1140",
    "name": "/1  เปี้ยก เจริญยนต์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1086",
    "name": "อู่ติเอง",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-869",
    "name": "นันท์เจริญยนต์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "16 : อ.สามโก้",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-938",
    "name": "ร้านอำนาจเจริญยนต์",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "19 : อ.ท่าช้าง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1580",
    "name": "เพิ่มพูลทวีการช่าง",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "21 : อ.ค่ายบางระจัน",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-147",
    "name": "คุณจารุวรรณ วัฒนกิจเจริญ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2076",
    "name": "ทองคำเจริญยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1166",
    "name": "อู่ประจบการช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1080",
    "name": "อู่ชัยโชคอัพ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1439",
    "name": "ช่างเหน่ง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1259",
    "name": "ปัญญาเกษตรยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-380",
    "name": "ร้านช่างชูชัย ศรีทองกูล",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1906",
    "name": "อู่เชิดการช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-750",
    "name": "ร้านเอกมอเตอร์ไซด์  (ด่านช้าง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "07 : อ.ด่านช้าง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-15",
    "name": "อู่อนุศักดิ์เซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "07 : อ.ด่านช้าง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1517",
    "name": "ช่างไพรัช  อินครุฑ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "10 : อ.หนองหญ้าไซ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-282",
    "name": "นุกุลเจริญยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "10 : อ.หนองหญ้าไซ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-891",
    "name": "/1  ร้านป.เจริญยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "10 : อ.หนองหญ้าไซ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1839",
    "name": "ร้านใหญ่เจริญยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "10 : อ.หนองหญ้าไซ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1944",
    "name": "นิคมมอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1831",
    "name": "มอเตอร์ช็อป",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1939",
    "name": "สไปร์ทคาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1671",
    "name": "แก้วการช่าง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-203",
    "name": "สองปอมอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-955",
    "name": "ช่างเณรมอเตอร์ไซต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1014",
    "name": "เขาเขียวยางยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1220",
    "name": "เตี้ยไดนาโม",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-233",
    "name": "เอส.พี.คาร์เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-1047",
    "name": "สุประดิษฐ์คาร์เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-143",
    "name": "อวยชัยยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-854",
    "name": "เม้งมอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2031",
    "name": "บริษัท ชัยชนะ เทรดดิ้ง จำกัด",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2040",
    "name": "ไกด์คาร์เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2102",
    "name": "ช่างแก่น",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-976",
    "name": "ตองห้าดีเซลช็อป (เอ็มคาร์แคร์)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "36 : อ.บรรพตพิสัย",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-1382",
    "name": "มลมอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1999",
    "name": "ช่างกรุง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2021",
    "name": "ศิริรัตน์พาณิชย์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-714",
    "name": "ว.มอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "42 : อ.ชุมตาบง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1314",
    "name": "ช่างจำนง",
    "province": "ชัยนาท",
    "dsrId": "DSR-ANN",
    "address": "31 : อ.มโนรมย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "109-63",
    "name": "ช่างสำลี",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1359",
    "name": "ร้านช่างแดง (เนินขาม) : วุฒิภัทรการช่าง",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "45 : อ.เนินขาม",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "109-271",
    "name": "ฮั้งเล้งการช่าง (ถ่วงฮี้การช่าง)",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "48 : อ.หันคา",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1424",
    "name": "รุ่งเรืองการเกษตร",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "48 : อ.หันคา",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "109-83",
    "name": "ศรีเมืองทอง",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "49 : อ.สรรคบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2118",
    "name": "รุ่งกิตติแอร์",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "49 : อ.สรรคบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-441",
    "name": "ร้านวิเชษฐ์มอเตอร์ไซต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-352",
    "name": "ร้านอึ่งมอเตอร์ไซต์(อุทัย)",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2033",
    "name": "อุทัยออโต้แอร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "50 : อ.เมือง อุทัยธานี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-538",
    "name": "ร้านช่างหมง",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1386",
    "name": "เบ๊นคาร์แคร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-635",
    "name": "ดี  ดี  การยาง",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-127",
    "name": "สุพัฒน์ยนต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "54 : อ.ทัพทัน",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-112",
    "name": "อู่สายชลยนต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "54 : อ.ทัพทัน",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-1320",
    "name": "รักรถคุณคาร์แคร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "56 : อ.หนองขาหย่าง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-163",
    "name": "ร้านช่างหม่อง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-339",
    "name": "ร้านแดงการช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1843",
    "name": "ร้านเทพไชยา",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-17",
    "name": "นายสมชาย (ดาวทอง คาร์แคร์)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "02 : อ.เดิมบางนางบวช",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-50",
    "name": "ช่างพิเชษฐ์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "03 : อ.สามชุก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1974",
    "name": "ช่างวรุฒ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "03 : อ.สามชุก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1470",
    "name": "ชาการช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "03 : อ.สามชุก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-713",
    "name": "ร้านวิริยะเซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "03 : อ.สามชุก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2115",
    "name": "ช่างประพันธ์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "04 : อ.ศรีประจันต์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-890",
    "name": "คุณสมเกียรติ  กระจายแสง",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "11 : อ.เมือง อ่างทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1274",
    "name": "อู่บุญญฤทธิ์การช่าง",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "17 : อ.แสวงหา",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1113",
    "name": "บุญชูมอไซค์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "13 : อ.ป่าโมก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1047",
    "name": "ร้านพีเจริญมอเตอร์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "13 : อ.ป่าโมก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1096",
    "name": "ฟลุ๊ค การาจ",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "13 : อ.ป่าโมก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1960",
    "name": "ช่างทัศน์ (มนต์การช่าง)",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1331",
    "name": "ร้านกัญชัยคาร์แคร์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "16 : อ.สามโก้",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2135",
    "name": "โค้กล้อแม็ก",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "16 : อ.สามโก้",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-371",
    "name": "ร้านเพชรลดามอเตอร์ (ประสิทธิ์ภาจำรัส)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1355",
    "name": "ช่างเพชร  (บ้านดอน)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-001",
    "name": "ร้านล้อยงศิลป์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "09 : อ.สองพี่น้อง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-359",
    "name": "อู่บุญมั่น รวมช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-415",
    "name": "อู่เต้ยเซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-381",
    "name": "ช่างธัญญา",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1434",
    "name": "ช่างดำ (อู่ทอง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1727",
    "name": "ช่างสามารถ",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1318",
    "name": "ร้านณัฐพลเซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-408",
    "name": "ร้านเพื่อนยานยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "07 : อ.ด่านช้าง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-129",
    "name": "ร้านชัชวาลย์พานิช",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "09 : อ.สองพี่น้อง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-206",
    "name": "ร้านเสรียนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "09 : อ.สองพี่น้อง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1052",
    "name": "ร้านชลันธรยานยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "09 : อ.สองพี่น้อง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-414",
    "name": "ส.เจริญยนต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "52 : อ.บ้านไร่",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1559",
    "name": "ช่างประเทือง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "25 : อ.พยุหะคีรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-323",
    "name": "ร้านศรียานยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-586",
    "name": "วิทยามอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-161",
    "name": "ร้าน จรันต์ยานยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2091",
    "name": "ช่างหนุ่ย",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-1025",
    "name": "เคพีเจริญยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "40 : อ.แม่วงก์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2004",
    "name": "ช่างม็อก",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "40 : อ.แม่วงก์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-367",
    "name": "เขาชนกัน คาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "40 : อ.แม่วงก์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-32",
    "name": "นพรัตน์ช่างยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "41 : อ.โกรกพระ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-91",
    "name": "คุณสุวัฒน์  จิตต์ฤกษ์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-561",
    "name": "แสงไชย มอเตอร์(สวง แสงไชย)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-970",
    "name": "/1  วีเอส คาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-996",
    "name": "ร้านไพบูลย์การช่าง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1595",
    "name": "รอมัย ยูนุช",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "26 : อ.ตาคลี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1363",
    "name": "ณุ เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "26 : อ.ตาคลี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-1057",
    "name": "เทคนิคเครื่องเย็น",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "27 : อ.ตากฟ้า",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2046",
    "name": "ช่างวิทย์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "28 : อ.ไพศาลี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-401",
    "name": "ส.เอมอเตอร์ไซค์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-791",
    "name": "/1  ร้านชาญชัย",
    "province": "ชัยนาท",
    "dsrId": "DSR-ANN",
    "address": "31 : อ.มโนรมย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "109-30",
    "name": "ภัทรลักษณ์กลการ",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "43 : อ.เมือง ชัยนาท",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-210",
    "name": "ชนะยนต์ (2B)",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1264",
    "name": "ช่างแจ๊ค",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-477",
    "name": "สงวนยนต์2",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "53 : อ.ลานสัก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1500",
    "name": "ช่างไร",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1177",
    "name": "ร้าน007 เซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1352",
    "name": "อู่เสน่ห์ คนรักรถ (ไผ่ขวาง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-51",
    "name": "/1  ช.รุ่งเรือง คาร์แคร์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1077",
    "name": "เจริญยนต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "02 : อ.เดิมบางนางบวช",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1411",
    "name": "ช่างตวง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "02 : อ.เดิมบางนางบวช",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1739",
    "name": "ช่างกอล์ฟยานยนต์ (เดิมบาง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "02 : อ.เดิมบางนางบวช",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1658",
    "name": "แม๊กนั่ม",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "03 : อ.สามชุก",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1101",
    "name": "ส.ประทีปยนต์",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "11 : อ.เมือง อ่างทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1242",
    "name": "ยอดเซอร์วิส",
    "province": "อ่างทอง",
    "dsrId": "DSR-ANN",
    "address": "11 : อ.เมือง อ่างทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1131",
    "name": "ร้านป่าโมกแอร์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "13 : อ.ป่าโมก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1050",
    "name": "คุณวรรณา  ทับทิมทอง",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2101",
    "name": "ช่างใหม่ อ่างทอง",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-810",
    "name": "คุณประสิทธิ์  กรผึ้ง (ร้านประสิทธิ์)",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2096",
    "name": "อภิออโต้ไทร์",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "15 : อ.วิเศษชัยชาญ",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1061",
    "name": "ร้านชลอการช่าง",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "16 : อ.สามโก้",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1321",
    "name": "ร้านช่างเก่ง  (สามโก้)",
    "province": "อ่างทอง",
    "dsrId": "DSR-NA",
    "address": "16 : อ.สามโก้",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2110",
    "name": "อู่ช่างอาร์ต",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2023",
    "name": "อมร เซอร์วิส",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "20 : อ.อินทร์บุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1751",
    "name": "อู่โอ๋เซอร์วิส",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "20 : อ.อินทร์บุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1269",
    "name": "ลุงหนวดคาร์แคร์",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "21 : อ.ค่ายบางระจัน",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2126",
    "name": "ทรัพย์พูลศรี เจริญยนต์",
    "province": "สิงห์บุรี",
    "dsrId": "DSR-KAN",
    "address": "21 : อ.ค่ายบางระจัน",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-2008",
    "name": "กิตติศักดิ์ คงอ่อน",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "05 : อ.ดอนเจดีย์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1591",
    "name": "ช่างสงกรานต์",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-171",
    "name": "อู่เปี๊ยกการช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1923",
    "name": "เลี๊ยบคาร์เซอร์วิส",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "06 : อ.อู่ทอง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-326",
    "name": "อู่เจริญยนต์ (ช่างแดง ด่านช้าง)",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NUCH",
    "address": "07 : อ.ด่านช้าง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-1933",
    "name": "ช่างประสิทธิ์ (ลาดยาว)",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-816",
    "name": "ร้านต.การช่าง",
    "province": "สุพรรณบุรี",
    "dsrId": "DSR-NA",
    "address": "01 : อ.เมือง สุพรรณบุรี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-23",
    "name": "ร้านผ่องโมดิฟาย",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1764",
    "name": "อัมรินทร์เซอร์วิส",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "33 : อ.เมือง นครสวรรค์",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-475",
    "name": "ร้านทรัพย์ถาวร",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "36 : อ.บรรพตพิสัย",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1870",
    "name": "ช่างน้อย",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "36 : อ.บรรพตพิสัย",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1542",
    "name": "เจริญการช่าง",
    "province": "นครสวรรค์",
    "dsrId": "DSR-MUD",
    "address": "38 : อ.ลาดยาว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-210",
    "name": "/1  ร้านไพรินมอเตอร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "24 : อ.ชุมแสง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "205-115",
    "name": "หจก.ส.สว่างรัตน์ยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "26 : อ.ตาคลี",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1415",
    "name": "บริษัท วัชรพลออโต้แม็กซ์ จำกัด",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "28 : อ.ไพศาลี",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "113-2005",
    "name": "พงษ์ภีระคาร์แคร์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "29 : อ.ท่าตะโก",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "205-255",
    "name": "ชูศักดิ์เจริญยนต์",
    "province": "นครสวรรค์",
    "dsrId": "DSR-ANN",
    "address": "30 : อ.หนองบัว",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "109-175",
    "name": "บรรเทิงมอเตอร์ไซค์",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "48 : อ.หันคา",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-740",
    "name": "ทวีการช่าง",
    "province": "ชัยนาท",
    "dsrId": "DSR-KAN",
    "address": "48 : อ.หันคา",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-294",
    "name": "สยามมอเตอร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-1381",
    "name": "ช่างออย",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "206-16",
    "name": "สมควรคาร์แคร์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-379",
    "name": "ร้านสุวรรณเจริญยนต์",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "51 : อ.หนองฉาง",
    "segment": "PCO (รถยนต์)"
  },
  {
    "id": "206-1395",
    "name": "ช่างจอย",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "56 : อ.หนองขาหย่าง",
    "segment": "MCO (มอเตอร์ไซค์)"
  },
  {
    "id": "113-1527",
    "name": "สมเกียรติยางยนต์ศูนย์ล้อ",
    "province": "อุทัยธานี",
    "dsrId": "DSR-KAN",
    "address": "56 : อ.หนองขาหย่าง",
    "segment": "PCO (รถยนต์)"
  }
];

export const initialTransactions = [
  {
    "id": "TXN-EARN-00001",
    "customerId": "113-1901",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 1956,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 59,
    "description": "สะสมงบ GTX 20W50 12X1L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00002",
    "customerId": "113-1901",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 3498,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 105,
    "description": "สะสมงบ GTX 20W50 3X4L R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00003",
    "customerId": "113-1901",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 4386,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 132,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00004",
    "customerId": "113-1901",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 6870,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 206,
    "description": "สะสมงบ MAG 10W40 3x4P1L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00005",
    "customerId": "113-1901",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 3840,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 115,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00006",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-04",
    "type": "earn",
    "amount": 2140,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 64,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00007",
    "customerId": "205-454",
    "dsrId": "DSR-ANN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 25,
    "description": "สะสมงบ POWER1 4T 10W-40 12X0.8L N จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00008",
    "customerId": "205-17",
    "dsrId": "DSR-ANN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3306,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 99,
    "description": "สะสมงบ MAG 10W40 3x4L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00009",
    "customerId": "205-17",
    "dsrId": "DSR-ANN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3840,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 115,
    "description": "สะสมงบ MAG PU 15W40 3x6P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00010",
    "customerId": "206-1002",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 6600,
    "qty": 5,
    "rate": 1.5,
    "promoVal": 99,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00011",
    "customerId": "206-1002",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 4392,
    "qty": 3,
    "rate": 1.5,
    "promoVal": 66,
    "description": "สะสมงบ ACTIV AT 20W40 12X0.8L SN R  จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00012",
    "customerId": "113-1016",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 6612,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 198,
    "description": "สะสมงบ MAG 10W40 3x4L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00013",
    "customerId": "113-1016",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 7680,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 230,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00014",
    "customerId": "113-1016",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3741,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 112,
    "description": "สะสมงบ MAG 5W30 3X4L_TH  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00015",
    "customerId": "113-1016",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3210,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 96,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00016",
    "customerId": "206-68",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 2640,
    "qty": 2,
    "rate": 1.5,
    "promoVal": 40,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00017",
    "customerId": "206-68",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 25,
    "description": "สะสมงบ POWER1 4T 10W30 12X0.8L SP R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00018",
    "customerId": "206-87",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 1320,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 20,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00019",
    "customerId": "206-87",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 1464,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 22,
    "description": "สะสมงบ ACTIV AT 20W40 12X0.8L SN R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00020",
    "customerId": "206-170",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3120,
    "qty": 2,
    "rate": 1.5,
    "promoVal": 47,
    "description": "สะสมงบ ACTIV 4T 20W40 12X1L SN R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00021",
    "customerId": "206-753",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 6720,
    "qty": 4,
    "rate": 1.5,
    "promoVal": 101,
    "description": "สะสมงบ POWER1 4T 10W-40 12X0.8L N จำนวน 4 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00022",
    "customerId": "206-753",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 2244,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 34,
    "description": "สะสมงบ POWER1 AT 10W40+SGO 12X0.92L จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00023",
    "customerId": "113-2116",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00024",
    "customerId": "113-2116",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 3435,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 103,
    "description": "สะสมงบ MAG 10W30 3x4P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00025",
    "customerId": "206-270",
    "dsrId": "DSR-KAN",
    "date": "2026-05-05",
    "type": "earn",
    "amount": 1320,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 20,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00026",
    "customerId": "113-248",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 2640,
    "qty": 2,
    "rate": 1.5,
    "promoVal": 40,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00027",
    "customerId": "113-248",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 6600,
    "qty": 5,
    "rate": 1.5,
    "promoVal": 99,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00028",
    "customerId": "113-248",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 1464,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 22,
    "description": "สะสมงบ ACTIV AT 20W40 12X0.8L SN R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00029",
    "customerId": "113-248",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 8940,
    "qty": 5,
    "rate": 1.5,
    "promoVal": 134,
    "description": "สะสมงบ ACTIV AT 20W40+SGO 12X0.92L จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00030",
    "customerId": "113-329",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 6600,
    "qty": 5,
    "rate": 1.5,
    "promoVal": 99,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00031",
    "customerId": "113-423",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 1464,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 22,
    "description": "สะสมงบ ACTIV AT 20W40 12X0.8L SN R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00032",
    "customerId": "113-1785",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 1890,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 57,
    "description": "สะสมงบ GTX DIESEL 20W50 3X5L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00033",
    "customerId": "113-1785",
    "dsrId": "DSR-NA",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 2193,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 66,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00034",
    "customerId": "113-16",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 3552,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 53,
    "description": "สะสมงบ POWER1 ULT AUTO 5W40 12X1L R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00035",
    "customerId": "113-715",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-06",
    "type": "earn",
    "amount": 19200,
    "qty": 5,
    "rate": 3.0,
    "promoVal": 576,
    "description": "สะสมงบ MAG PU 15W40 3x6P1L_TH จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00036",
    "customerId": "113-869",
    "dsrId": "DSR-NA",
    "date": "2026-05-07",
    "type": "earn",
    "amount": 3435,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 103,
    "description": "สะสมงบ MAG 10W30 3x4P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00037",
    "customerId": "113-869",
    "dsrId": "DSR-NA",
    "date": "2026-05-07",
    "type": "earn",
    "amount": 3435,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 103,
    "description": "สะสมงบ MAG 10W40 3x4P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00038",
    "customerId": "113-869",
    "dsrId": "DSR-NA",
    "date": "2026-05-07",
    "type": "earn",
    "amount": 7680,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 230,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00039",
    "customerId": "113-147",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1320,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 20,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00040",
    "customerId": "113-147",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1788,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 27,
    "description": "สะสมงบ ACTIV AT 20W40+SGO 12X0.92L จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00041",
    "customerId": "113-1080",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 4128,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 124,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00042",
    "customerId": "113-1080",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00043",
    "customerId": "113-1080",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00044",
    "customerId": "113-1080",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 7680,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 230,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00045",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 2064,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 62,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00046",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00047",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00048",
    "customerId": "113-380",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1320,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 20,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00049",
    "customerId": "113-380",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 25,
    "description": "สะสมงบ POWER1 4T 10W-40 12X0.8L N จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00050",
    "customerId": "113-1906",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 3840,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 115,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00051",
    "customerId": "113-750",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1320,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 20,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00052",
    "customerId": "113-750",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1464,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 22,
    "description": "สะสมงบ ACTIV AT 20W40 12X0.8L SN R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00053",
    "customerId": "113-750",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 1932,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 29,
    "description": "สะสมงบ POWER1 AT 10W40 12X0.8L SP R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00054",
    "customerId": "113-282",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 19200,
    "qty": 5,
    "rate": 3.0,
    "promoVal": 576,
    "description": "สะสมงบ MAG PU 10W30 3x6P1L_TH จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00055",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00056",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-08",
    "type": "earn",
    "amount": 8118,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 244,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00057",
    "customerId": "113-1220",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 2193,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 66,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00058",
    "customerId": "205-233",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 3840,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 115,
    "description": "สะสมงบ MAG PU 15W40 3x6P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00059",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 6846,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 205,
    "description": "สะสมงบ VISCO PU 3000 15W40 3X6F1 HL  จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00060",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 2520,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 76,
    "description": "สะสมงบ GTX DIESEL 10W30 3X6P1L R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00061",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 6192,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 186,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00062",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00063",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 3927,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 118,
    "description": "สะสมงบ MAG PU 10W-30_PS_CK4_3X6P1L จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00064",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 2140,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 64,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00065",
    "customerId": "113-715",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 3498,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 105,
    "description": "สะสมงบ GTX 20W50 3X4L R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00066",
    "customerId": "113-715",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 5040,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 151,
    "description": "สะสมงบ GTX DIESEL 10W30 3X6P1L R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00067",
    "customerId": "113-715",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-11",
    "type": "earn",
    "amount": 27216,
    "qty": 7,
    "rate": 3.0,
    "promoVal": 816,
    "description": "สะสมงบ MAG 5W30 3X4P1L_TH  จำนวน 7 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00068",
    "customerId": "206-1002",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 25,
    "description": "สะสมงบ POWER1 4T 10W-40 12X0.8L N จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00069",
    "customerId": "113-2033",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 6192,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 186,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00070",
    "customerId": "113-2033",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 11223,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 337,
    "description": "สะสมงบ MAG 5W30 3X4L_TH  จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00071",
    "customerId": "113-2033",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 3741,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 112,
    "description": "สะสมงบ MAG 0W20 1x3.5P1L_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00072",
    "customerId": "206-538",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 3120,
    "qty": 2,
    "rate": 1.5,
    "promoVal": 47,
    "description": "สะสมงบ ACTIV 4T 20W40 12X1L SN R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00073",
    "customerId": "206-635",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 4386,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 132,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00074",
    "customerId": "206-635",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 1070,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 32,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00075",
    "customerId": "206-127",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 10560,
    "qty": 8,
    "rate": 1.5,
    "promoVal": 158,
    "description": "สะสมงบ ACTIV 4T 20W40 12X0.8L SN R จำนวน 8 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00076",
    "customerId": "206-127",
    "dsrId": "DSR-KAN",
    "date": "2026-05-12",
    "type": "earn",
    "amount": 3360,
    "qty": 2,
    "rate": 1.5,
    "promoVal": 50,
    "description": "สะสมงบ POWER1 4T 10W-40 12X0.8L N จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00077",
    "customerId": "113-163",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 25,
    "description": "สะสมงบ POWER1 4T 10W30 12X0.8L SP R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00078",
    "customerId": "113-163",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 1932,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 29,
    "description": "สะสมงบ POWER1 AT 10W40 12X0.8L SP R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00079",
    "customerId": "113-248",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 1788,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 27,
    "description": "สะสมงบ ACTIV AT 20W40+SGO 12X0.92L จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00080",
    "customerId": "113-82",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 6192,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 186,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00081",
    "customerId": "113-82",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00082",
    "customerId": "113-17",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 5247,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 157,
    "description": "สะสมงบ GTX 20W50 3X4L R จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00083",
    "customerId": "113-17",
    "dsrId": "DSR-NA",
    "date": "2026-05-13",
    "type": "earn",
    "amount": 12600,
    "qty": 5,
    "rate": 3.0,
    "promoVal": 378,
    "description": "สะสมงบ GTX DIESEL 10W30 3X6P1L R จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00084",
    "customerId": "113-1274",
    "dsrId": "DSR-ANN",
    "date": "2026-05-14",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00085",
    "customerId": "113-1047",
    "dsrId": "DSR-NA",
    "date": "2026-05-14",
    "type": "earn",
    "amount": 1932,
    "qty": 1,
    "rate": 1.5,
    "promoVal": 29,
    "description": "สะสมงบ POWER1 AT 10W40 12X0.8L SP R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00086",
    "customerId": "113-1080",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00087",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 2064,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 62,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00088",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00089",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00090",
    "customerId": "113-415",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 6192,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 186,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00091",
    "customerId": "113-715",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-15",
    "type": "earn",
    "amount": 11664,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 350,
    "description": "สะสมงบ MAG 5W30 3X4P1L_TH  จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00092",
    "customerId": "206-414",
    "dsrId": "DSR-KAN",
    "date": "2026-05-16",
    "type": "earn",
    "amount": 6870,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 206,
    "description": "สะสมงบ MAG 10W30 3x4P1L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00093",
    "customerId": "205-233",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 3306,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 99,
    "description": "สะสมงบ MAG 10W40 3x4L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00094",
    "customerId": "205-1047",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00095",
    "customerId": "205-1047",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 5412,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 162,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00096",
    "customerId": "205-854",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 5350,
    "qty": 5,
    "rate": 3.0,
    "promoVal": 160,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 5 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00097",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 9042,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 271,
    "description": "สะสมงบ MAG PU 5W-30_3X6P1L_TH (new spec ACEA C3) จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00098",
    "customerId": "205-996",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00099",
    "customerId": "205-996",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00100",
    "customerId": "206-1363",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2064,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 62,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00101",
    "customerId": "206-1363",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00102",
    "customerId": "206-1363",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00103",
    "customerId": "206-1363",
    "dsrId": "DSR-ANN",
    "date": "2026-05-18",
    "type": "earn",
    "amount": 4521,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 136,
    "description": "สะสมงบ MAG PU 5W-30_3X6P1L_TH (new spec ACEA C3) จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00104",
    "customerId": "113-329",
    "dsrId": "DSR-NA",
    "date": "2026-05-20",
    "type": "earn",
    "amount": 5364,
    "qty": 3,
    "rate": 1.5,
    "promoVal": 80,
    "description": "สะสมงบ ACTIV AT 20W40+SGO 12X0.92L จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00105",
    "customerId": "113-1131",
    "dsrId": "DSR-NA",
    "date": "2026-05-21",
    "type": "earn",
    "amount": 1956,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 59,
    "description": "สะสมงบ GTX 20W50 12X1L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00106",
    "customerId": "113-1131",
    "dsrId": "DSR-NA",
    "date": "2026-05-21",
    "type": "earn",
    "amount": 26187,
    "qty": 7,
    "rate": 3.0,
    "promoVal": 786,
    "description": "สะสมงบ MAG 5W30 3X4L_TH  จำนวน 7 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00107",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-21",
    "type": "earn",
    "amount": 3168,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 95,
    "description": "สะสมงบ MAG PU 10W30 12x1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00108",
    "customerId": "113-1166",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 3780,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 113,
    "description": "สะสมงบ GTX DIESEL 20W50 3X5L R  จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00109",
    "customerId": "113-1166",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 4386,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 132,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00110",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 2064,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 62,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00111",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 15W40 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00112",
    "customerId": "113-1439",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 2706,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 81,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00113",
    "customerId": "113-171",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 2193,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 66,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00114",
    "customerId": "113-1923",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 20640,
    "qty": 10,
    "rate": 3.0,
    "promoVal": 619,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 10 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00115",
    "customerId": "113-1923",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 27060,
    "qty": 10,
    "rate": 3.0,
    "promoVal": 812,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 10 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00116",
    "customerId": "113-326",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 7560,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 227,
    "description": "สะสมงบ GTX DIESEL 15W40 3X6P1L R จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00117",
    "customerId": "113-326",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 8118,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 244,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00118",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 2064,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 62,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00119",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 10824,
    "qty": 4,
    "rate": 3.0,
    "promoVal": 325,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 4 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00120",
    "customerId": "113-891",
    "dsrId": "DSR-NUCH",
    "date": "2026-05-22",
    "type": "earn",
    "amount": 9504,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 285,
    "description": "สะสมงบ MAG PU 10W30 12x1L_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00121",
    "customerId": "113-1220",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 1749,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 52,
    "description": "สะสมงบ GTX 20W50 3X4L R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00122",
    "customerId": "113-1220",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 1680,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 50,
    "description": "สะสมงบ GTX DIESEL 10W30 12X1L R จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00123",
    "customerId": "113-1220",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3168,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 95,
    "description": "สะสมงบ MAG PU 10W30 12x1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00124",
    "customerId": "113-1220",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 2140,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 64,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00125",
    "customerId": "205-143",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3306,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 99,
    "description": "สะสมงบ MAG 10W30 3x4L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00126",
    "customerId": "205-143",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3435,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 103,
    "description": "สะสมงบ MAG 10W30 3x4P1L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00127",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 5040,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 151,
    "description": "สะสมงบ GTX DIESEL 15W40 3X6P1L R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00128",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 5040,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 151,
    "description": "สะสมงบ GTX DIESEL 10W30 3X6P1L R จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00129",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 4128,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 124,
    "description": "สะสมงบ GTX 10W40 3X4L_PS_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00130",
    "customerId": "205-976",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 8118,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 244,
    "description": "สะสมงบ GTX DS 10W30 3X6P1L_PS_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00131",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3306,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 99,
    "description": "สะสมงบ MAG 10W30 3x4L_TH จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00132",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 7854,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 236,
    "description": "สะสมงบ MAG PU 10W-30_PS_CK4_3X6P1L จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00133",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3741,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 112,
    "description": "สะสมงบ MAG 5W30 3X4L_TH  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00134",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 2140,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 64,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00135",
    "customerId": "205-994",
    "dsrId": "DSR-MUD",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 9042,
    "qty": 2,
    "rate": 3.0,
    "promoVal": 271,
    "description": "สะสมงบ MAG PU 5W-30_3X6P1L_TH (new spec ACEA C3) จำนวน 2 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00136",
    "customerId": "205-17",
    "dsrId": "DSR-ANN",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 2193,
    "qty": 1,
    "rate": 3.0,
    "promoVal": 66,
    "description": "สะสมงบ GTX DIESEL 20W50 3X6L R  จำนวน 1 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-EARN-00137",
    "customerId": "205-973",
    "dsrId": "DSR-ANN",
    "date": "2026-05-25",
    "type": "earn",
    "amount": 3210,
    "qty": 3,
    "rate": 3.0,
    "promoVal": 96,
    "description": "สะสมงบ MAG 0W20 1x3.5L_TH จำนวน 3 ลัง",
    "status": "approved",
    "receiptUrl": ""
  },
  {
    "id": "TXN-CLAIM-MOCK-001",
    "customerId": "113-715",
    "dsrId": "DSR-MUD",
    "date": "2026-05-18",
    "type": "claim",
    "amount": 0,
    "qty": 0,
    "rate": 0,
    "promoVal": 1500,
    "description": "แลกพัดลม Hatari 16 นิ้ว มอบให้ลูกค้าช่างซ่อม",
    "status": "approved",
    "receiptUrl": "data:image/svg+xml;charset=utf-8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"300\" height=\"400\" viewBox=\"0 0 300 400\"><rect width=\"100%\" height=\"100%\" fill=\"%23f1f5f9\"/><text x=\"50%\" y=\"20%\" font-family=\"sans-serif\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"%231e293b\">ใบเสร็จรับเงิน / Receipt</text><text x=\"10%\" y=\"35%\" font-family=\"sans-serif\" font-size=\"12\" fill=\"%23475569\">ร้านเครื่องไฟฟ้าปากน้ำโพ</text><text x=\"10%\" y=\"45%\" font-family=\"sans-serif\" font-size=\"12\" fill=\"%23475569\">รายการ: พัดลม Hatari 16 นิ้ว</text><text x=\"10%\" y=\"65%\" font-family=\"sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"%231e293b\">ยอดรวม: 1,500 บาท</text><line x1=\"10%\" y1=\"75%\" x2=\"90%\" y2=\"75%\" stroke=\"%23cbd5e1\" stroke-width=\"2\"/></svg>",
    "deliveryPhotoUrl": "data:image/svg+xml;charset=utf-8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"300\" height=\"200\" viewBox=\"0 0 300 200\"><rect width=\"100%\" height=\"100%\" fill=\"%23d1fae5\"/><text x=\"50%\" y=\"50%\" font-family=\"sans-serif\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"%23065f46\">รูปถ่ายส่งมอบพัดลมสำเร็จ</text></svg>"
  },
  {
    "id": "TXN-CLAIM-MOCK-002",
    "customerId": "113-1923",
    "dsrId": "DSR-MUD",
    "date": "2026-05-24",
    "type": "claim",
    "amount": 0,
    "qty": 0,
    "rate": 0,
    "promoVal": 800,
    "description": "เตาไฟฟ้าหุงต้ม อุปกรณ์ช่างอู่รถ",
    "status": "pending",
    "receiptUrl": "data:image/svg+xml;charset=utf-8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"300\" height=\"400\" viewBox=\"0 0 300 400\"><rect width=\"100%\" height=\"100%\" fill=\"%23f1f5f9\"/><text x=\"50%\" y=\"20%\" font-family=\"sans-serif\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"%231e293b\">บิลเงินสด</text><text x=\"10%\" y=\"45%\" font-family=\"sans-serif\" font-size=\"12\" fill=\"%23475569\">รายการ: เตาไฟฟ้าหุงต้ม</text><text x=\"10%\" y=\"65%\" font-family=\"sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"%231e293b\">ยอดรวม: 800 บาท</text></svg>"
  }
];
